Feat/financial-date-functions
RHDZMOTA/cashflows pull request #2
Opened 2018-01-12 01:40 UTC by RHDZMOTA

This pull request provides the following functionality:
- Time object for different time-types (integer and date-time).
- Financial functions (xirr and xnpv) for cash flows subject to a particular date.
- Implementation of xirr and xnpv in the main cashflow object.

2018-01-15 20:40 UTC, joseluisvaz commented on .idea/other.xml
> +</project>
Add .idea to .gitignore

2018-01-15 21:04 UTC, joseluisvaz commented on README.md
> +#### Run the tests
Add instructions to create a venv inside the README.md

2018-01-15 21:04 UTC, joseluisvaz commented on .idea/other.xml
> +</project>
Add .idea to .gitignore, and remove this folder form github using git rm

2018-01-15 21:04 UTC, joseluisvaz commented on cashflows/financial_functions.py
> +    return npv
val = flow.value * np.power(1 + rate, -year)
if flow.type == "outflow":
    val *= -1

2018-01-15 21:04 UTC, joseluisvaz commented on cashflows/financial_functions.py
> +        return scipy.optimize.newton(lambda r: xnpv(sorted_flows, r, year_days), 0.0)
Name of function parameters scipy.optimize.newton(lambda r: ... , x0 = 0.0)

2018-01-15 21:04 UTC, joseluisvaz commented on cashflows/financial_functions.py
> +        return scipy.optimize.brentq(lambda r: xnpv(sorted_flows, r, year_days), -1, 100)
Same as above

2018-01-15 21:04 UTC, joseluisvaz commented on cashflows/flows.py
> +from .financial_functions import *
Read PEP-8, never do global imports

2018-01-15 21:04 UTC, joseluisvaz commented on cashflows/flows.py
> +from datetime import datetime
Imports from standard libraries come before imports from user defined libraries.

2018-01-23 17:41 UTC, joseluisvaz requested changes

2018-01-23 17:41 UTC, joseluisvaz commented on cashflows/financial_functions.py
> +    return npv
flow.value * (1+rate)**(-year)
if flow.type == "outflow"
    val *= -1

2018-01-23 17:41 UTC, joseluisvaz commented on cashflows/flows.py
> +import warnings
import warnings first, check pep-8 for order of imports

Imports should be grouped in the following order:

standard library imports
related third party imports
local application/library specific imports
You should put a blank line between each group of imports.

2018-01-23 17:41 UTC, joseluisvaz commented on cashflows/flows.py
> +
Same as above, send datetime up, and dateutil down

2018-01-23 17:53 UTC, joseluisvaz requested changes

2018-01-23 17:53 UTC, joseluisvaz commented on cashflows/flows.py
> +class Time(object):
Make an object per class

2018-01-23 18:12 UTC, RHDZMOTA commented on cashflows/flows.py
> +class Time(object):
**make a file per class

2018-01-23 19:22 UTC, joseluisvaz approved these changes
Change inflow and outflow to +and -

Change Flow to CashFlow and CashFlow to CashFlowSeries

2018-01-23 19:22 UTC, joseluisvaz commented on cashflows/flow.py
> +        return str(self)
erase to string method

2018-01-23 19:22 UTC, joseluisvaz commented on cashflows/flow.py
> +    def __init__(self, flow_type, value, time, time_type="int", currency="mxn"):
Add docstring specifing the meaning of the object properties, and the values that they can take

2018-01-23 19:22 UTC, joseluisvaz commented on cashflows/flow.py
> +            this_time=self.time.to_string(),
self.time.to_string() -> str(self.time)

2018-01-24 18:47 UTC, merged